// #define USE_SERIAL
// Using Serial instead of I2C
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_PIO_USE_PIO0
#define SERIAL_USART_TIMEOUT     100  // USART driver timeout. default 100
#define SERIAL_USART_SPEED 921600

#ifdef OLED_ENABLE
#define I2C_DRIVER I2CD0
#define I2C0_SDA_PIN GP28
#define I2C0_SCL_PIN GP29
// OLED Options
#define SPLIT_OLED_ENABLE
#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 60000
#endif
