// Copyright 2024 Matthew Pardue (caracarn)
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#ifndef CONFIG_USER_H
    #define CONFIG_USER_H
#endif

#undef FORCE_NKRO
#define FORCE_NKRO

#ifdef SMART_CASE_ENABLE
    #define CUSTOM_ONESHOT_TIMEOUT 2000
#endif

#define SPLIT_POINTING_ENABLE
#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_RIGHT
#define PMW33XX_CS_PIN GP13
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define PMW33XX_LIFTOFF_DISTANCE 0x02
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1200
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200
#define CHARYBDIS_DRAGSCROLL_DPI 100
#define CHARYBDIS_POINTER_ACCELERATION_ENABLE
// #define CHARYBDIS_DRAGSCROLL_REVERSE_Y
#define AUTO_MOUSE_TIME 500

#ifdef OLED_ENABLE
#   define OLED_FONT_H "keyboards/handwired/dactyl_manuform/5x6_63/keymaps/coramoor/glcdfont.c"
#   define OLED_TIMEOUT 60000
#   define SPLIT_LAYER_STATE_ENABLE
#   define SPLIT_LED_STATE_ENABLE
#   define SPLIT_MODS_ENABLE
#   define SPLIT_OLED_ENABLE
#endif
